apiVersion: v1
kind: Pod
metadata:
  name: salvatore
  labels:
    run: salvatore
    service: webserver
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    args: ["sleep", "1800"]
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
