apiVersion: v1
kind: Pod
metadata:
  name: salvatore
  labels:
    run: salvatore
    service: webserver
spec:
  containers:
  - name: webserver
    image: nginx
    volumeMounts:
    - mountPath: /salvatore
      name: first-emptydir
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: first-emptydir
    emptyDir:
      sizeLimit: 256Mi
