apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: salazar
    service: webserver
  name: salazar
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: busybox 
    name: busybox
    args:
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
