apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None # Aqui [e onde o ~headless~ [e viabilizado
  selector:
    app: nginx
