apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: jon
  labels:
    app: nginx-deployment
    race: ainu
spec:
  replicas: 14
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: 
    type: Recreate
  template: 
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - image: nginx:1.17.0
          name: nginx-new
          resources:
            limits:
              cpu: 0.9
              memory: 156Mi  
            requests:
              cpu: 0.4
              memory: 64Mi
