apiVersion: v1
kind: PersistentVolume
metadata: 
  labels:
    storage: nfs
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes: 
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /mnt/data
  storageClassName: jon
