apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  labels:
    pvc: my-first-pvc
    storage: nfs
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#  storageClassName: jon
  selector:
    matchLabels:
      storage: nfs
